sudo: required
dist: trusty
language: go

go:
  - 1.9

install:
- curl -sSL "https://get.docker.com/gpg" | sudo -E apt-key add -
- echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes --force-yes install docker-engine
- sudo docker version
- sudo pip install docker-compose
- docker-compose version

before_script:
- docker-compose -f $TRAVIS_BUILD_DIR/test-dependencies.yml up -d

script:
- make test
